var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                                 xx!xx          ",
   "                                    o o                          x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "                                           o                                 x  ",
   "  x                     o                                                    x  ",
   "  x                   xxxxxx              xxx                                x  ",
   "  x          xxxx                                                  o         x  ",
   "  x  @      !!!!!!                   p                           xxxxx       x  ",
   "  xxxxxxx!!!!!!!!!!!!!!xxxxxxxx   xxxxxxx     xxxxxxxx     xxxxxxx!!!xxxxxxxxx  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!x!!!!!!!!!!!!!!!!!!x!!!!!x!!!!!!!!!!!!!!!!!!  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!  ",
   "                                                                                ",
   "                       o              o           o              k              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                       v                                                     x!x  ",
   "                                                                                                             x!x  ",
   "                                         k      o                                                            x!x  ",
   "                                      xxxxxxxxxxxxxx                                                         x!x  ",
   "                                       xxxxxxxxxx!!xx                                                     o  x!x  ",
   "                                                xx!x     xxxxx                                              xx!x  ",
   "                                                 x!x p          xxxx   o                      xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvxxxx              x              x                        =xx  ",
   "                                                                       x            xxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                         x                                        ",
   "                                                                           xxxxxxxx                               ",
   "                                        x =                            x                                          ",
   "                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          ",
   "                                                                                                                  ",
   "                                                                          xxxxxxxxxxxxxxxx                        ",
   "                                                                                                                  ",
   "  @                                                                  xxxx                                         ",
   "xxxxxxxxxxxxxxxxxxxxxx                                   xxxxx       x                                            ",
   "xxxxxxxxxxxxxxxx     xx                                              x                                            ",
   "xxxxxxxxxxxxxxx       xx                   o  o                   xxxx                                            ",
   "xxxxxxxxxxxxxx         x                  xxxxxx       xxx                                                        ",
   "xxxxxxxxxxxxxx         x                           xxx       xxxx                                                 ",
   "xxxxxxxxxxxxxx         x                  v  v       x                                                            ",
   "!!!!x x!!!!!!x         x                             x!!!!!!!!!!                                                  ",
   "!!!!x x!!!!!!x         x              xxxx xx xx     x!!!!!!!xx!                                                  ",
   "!!!!x x!!!!!!x         x                            xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x o                      o  xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         xxx            xxxxxxxxxxxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "  xxxxxxxxx                                                                                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "        xxxxxxxxxxxx         xxxxxxxxx                                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                   xxxxxxxxxxx                                                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                               xxxxxxxxxx        xxxxx                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                        xxxxxxxxxx                                            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                          xxxxxxxxx                                                           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                           xxxxxxxxx                                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                       xxxxxx                                                                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                          xxxxxxxx                                                            ",
   "                                                                                                              ",
   "                                                       o                                                      ",
   "                                                     xxxxx                                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                             p k p                                                            ",
   "                                               x                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                        x       x                                                                             ",
   "                         x     x   xxxxxxxx    x      x        x                   x                          ",
   "                          x   x    x      x    x      x         x                 x    x    xx     x          ",
   "                           x x     x      x    x      x          x               x     x    x x    x          ",
   "                            x      x      x    x      x           x             x      x    x  x   x          ",
   "                            x      x      x    x      x            x     x     x       x    x   x  x          ",
   "                            x      x      x    x      x             x   x x   x        x    x    x x          ",
   "                            x      x      x    x      x              x x   x x         x    x     xx          ",
   "                            x      xxxxxxxx    xxxxxxxx               x     x          x    x      x          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                 @                  p         k                               ",
   "                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
